name: Apply new changes to SolEng repositories

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - workflows/**

concurrency:
      # We do not want to run multiple jobs for single PR.
      group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
      cancel-in-progress: true

jobs:
  workflows:
    name: Run workflows update
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          repository:
            - charm-advanced-routing
          branch: [main]
          check_template: [charm-check.yaml.j2]
          owner: [rgildein]
          runs_on: ["[[ubuntu-24.04]]"]
          test_command: ["['tox -e func']"]

    steps:
      - name: Checkout automation repo
        uses: actions/checkout@v4
      - name: Checkout ${{ matrix.repository }}

        uses: actions/checkout@v4
        with:
          path: ./.tmp
          repository: ${{ matrix.owner }}/${{ matrix.repository }}
          ref: ${{ matrix.branch }}
      - name: Rendering check workflow template
        uses: cuchi/jinja2-action@v1.2.2
        with:
          template: ./workflows/${{ matrix.check_template }}
          output_file: ./.tmp/.github/workflows/check.yaml
          variables: |
            runs_on=${{ matrix.runs_on }}
            test_command=${{ matrix.test_command }}
      - name: Print git diff
        working-directory: ./.tmp
        run: git --no-pager diff
      - if: github.event.pull_request.draft == false
        name: Create pull request
        uses: canonical/create-pull-request@main
        with:
          upsert: true  # Allow update PRs
          base: stable/${{ inputs.openstack-release }}  # the target branch for the PR
          github-token: ${{ matrix.branch }}
          branch-name: ${{ github.head_ref }}
          repository: ${{ matrix.owner }}/${{ matrix.repository }}
          title: "chore(workflows): Automation update of GitHub workflows"
          body: "This pull request was generated by ${{ github.ref }}."
          commit-message: "Atomated update of workflow by ${{ github.ref }}."
